#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp

# Check if less than 3 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file to the server's home directory
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$server_ip":~/ 

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Failed to transfer file"
fi

