#!/usr/bin/env bash
# Process and PID file

# Function to clean up and terminate the script
cleanup() {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 0
}

# Function to handle SIGTERM and SIGQUIT signals
trap 'cleanup' SIGTERM SIGQUIT

# Function to handle SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
	echo "To infinity and beyond"
	sleep 1
done

