#!/usr/bin/env bash
# This script tells the story of /etc/passwd using the while loop + IFS

# Use a while loop to read each line from /etc/passwd
while IFS=: read -r username _ userid groupid info homedir shell; do
    passcode=$(echo "$info" | cut -d ' ' -f 2-)
    useridinfo=$(echo "$info" | cut -d ',' -f 2-)

    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $useridinfo"
done < /etc/passwd
