#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and superstitions based on certain iterations

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            # Display the current number for other iterations
            echo "$counter"
            ;;
    esac

    ((counter++))
done

