#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash

for file in *; do
	if [ "${file:0:1}" != "." ]; then
        name_part="${file#*-}"
        echo "$name_part"
    fi
done

