#!/bin/bash

# Update package list
sudo apt update

# Install ufw
sudo apt install ufw

# Enable ufw
sudo ufw enable

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Check the ufw status
sudo ufw status

