#!/usr/bin/env bash
# Display all active IPv4 IPs on the machine

# Use the 'ip' command to retrieve IPv4 addresses for interfaces in a global scope
ip -o -4 addr show scope global | awk '{split($4, a, "/"); print a[1]}'

